name: 'HTML Preview'
author: 'Pavitra Golchha | @pavi2410'
description: 'Preview HTML page'
inputs:
  html_file:
    description: 'The HTML file you want to preview, relative to the root of the repo'
    required: true
    default: 'index.html'
outputs:
  url:
    description: 'The URL of the HTML file specific to this build'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'orange'
  icon: 'eye'
