name: Test

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      - uses: actions/checkout@v4
      - name: Get HTML preview link
        id: html_preview
        uses: ./ # NOTE: replace with the latest version of this Action
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format('[Click here to preview the HTML page in your browser]({0})', steps.html_preview.outputs.url) }}
