name: 'HTML Preview Action'
on: [pull_request]

jobs:
  html_preview:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      - uses: actions/checkout@v2
      - name: Get HTML preview link
        uses: pavi2410/html-preview-action@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
